name: Deploy to Local Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t devonedev/premier-design:latest .

      - name: SSH to server and deploy
        uses: appleboy/scp-action@v0.1.3
        with:
          host: 192.168.100.168
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "."
          target: "/var/www/pd-app"

      - name: SSH to server and run docker-compose
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 192.168.100.168
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/pd-app
            docker-compose down
            docker-compose up -d --build
